#!/usr/bin/env bash
echo "Loading aliases ..."

local EDITOR="nvim"
local CONFIG="$HOME/.config"

#temp
export WM_CONFIG="$HOME/.config/hypr/"

hash -d c="$HOME/.config/"
hash -d d="$HOME/.dotfiles/"
hash -d p="$HOME/projects/"
hash -d v="$CONFIG/nvim/"
hash -d z="$CONFIG/zsh/"
hash -d t="/tmp/"
hash -d b="$HOME/.bin/"
hash -d w="$WM_CONFIG"

# xset r rate 300 30 # Input delay rate
function a() {
	if [ "$1" = "mimir" ]; then
		~b/sleep.sh
	fi
}

# shortcuts
alias b="bash"
alias r="ranger"
alias {c,cl,cle,clea}="clear"
alias cdot="cd $HOME/.dotfiles"
alias {v,e,vim}="nvim"

# configs
alias bc="$EDITOR $HOME/.bashrc"			# Bash config
alias vc="cd $CONFIG/nvim && $EDITOR"		# Nvim config
alias wc="$EDITOR $WM_CONFIG"				# Window Manager Config
alias tc="$EDITOR $HOME/.tmux.conf"			# Tmux config

# gnu
# alias cp="cp -i" # Confirm before overwriting
# alias mv="mv -i" #      --/--     moving/renaming
# alias rm="rm -i" #      --/--     deleting
alias grep="grep --color=auto"

# zsh 
alias {zr,zsh}="source $HOME/.zshrc"
alias zc="$EDITOR $ZDOTDIR"
alias za="$EDITOR $ZDOTDIR/modules/aliases"    # Alises
alias ze="$EDITOR $ZDOTDIR/modules/exports"    # Exports

# system commands
alias log{out,off}="pkill -KILL -u $USER"
alias sayonara="shutdown -h now"
alias supersudo="sudo --preserve-env=PATH env"
alias {u,aupdate}="yay -Syyuu --noconfirm"

# tools and applications
## exa & bat & zoxide
alias exa="exa --time-style=long-iso --git --group-directories-first --icons --no-permissions --no-user"
alias cat="bat --style full --theme Dracula"

alias l="exa -l"      # list files
alias ls="exa"       # list files in a table
alias la="ls -ah"     # list files hidden
alias lla="l -@lah" # list files in a table hidden
alias lt="ls -T"     # list tree
alias lta="ls -Ta"   # list tree hidden

## terminals
### kitty
alias kc="$EDITOR $HOME/.config/kitty/kitty.conf"

## rust
alias cr="cargo run"
alias cb="cargo build"
alias ct="cargo test"
alias cc="cargo clippy --fix -- -W clippy::pedantic -W clippy::nursery -W clippy::unwrap_used"
alias rs="rustup stable"
alias rn="rustup nightly"
## git
alias gs="git-st"
alias gc="git commit -m"
alias gl="git lg"
alias glo="git log --oneline"
alias ga="git add"
alias lg="lazygit"

alias ip="curl -s https://api.ipify.org; echo"

## emacs
alias cemacs="emacsclient -c -a 'emacs'"

## docker
alias di="docker image"
alias dv="docker volume"
alias dc="docker container"

echo "Aliases loaded"

## misc
alias obs="~/.bin/obs-launcher.sh &"

function starship_transient_prompt_func(prompt)
  return io.popen("starship module character"
    .." --keymap="..rl.getvariable('keymap')
  ):read("*a")
end
load(io.popen('starship init cmd'):read("*a"))()
