#!/bin/sh

autoload -Uz compinit
compinit

eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
eval "$(rtx complete --shell zsh)"

# Node Version Manager
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

zmodload zsh/complist
zstyle ':completion:*' menu select
zstyle ':completion:*:messages' format ' %F{purple} -- %d --%f'
zstyle ':completion:*:warnings' format ' %F{red}-- no matches found --%f'

$ZDOTDIR/modules/completions/_cargo
$ZDOTDIR/modules/completions/_rtx

# eval "$(jenv init zsh)"

eval "$(jenv init -)"
