#!/usr/bin/env bash

export EDITOR="nvim"
export BROWSER="brave"
export TERMINAL="kitty"
export ZDOTDIR="$HOME/.config/zsh"
export {MYVIMRC,VIMRC}="$HOME/.config/nvim/init.lua"
export JAVA="$(jenv which)"
export GOPATH="$HOME/.local/go"
export PATH="$PATH:$HOME/.bin:$HOME/.cargo/bin:$HOME/.local/bin:$HOME/.emacs.d/bin:$HOME/.jenv/bin:$GOPATH/bin:$HOME/.cargo/env"
