#!/bin/sh

bindkey -s ^o 'zi\n'
bindkey -s ^f 'tmux_sessionizer\n'
bindkey -s ^e 'nvim\n'

bindkey '^l' autosuggest-accept

# Control-Space:
# bindkey '^ ' list-expand

zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end


bindkey '\C-\177' backward-kill-word
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^K' history-beginning-search-backward-end
bindkey '^J' history-beginning-search-forward-end

export KEYTIMEOUT=1
