#!/bin/sh

fpath=(~/newdir $fpath)
stty stop undef # Disable ctrl-s to freeze terminal 
zle_highlight=('paste:none') # Remove text's highilight when pasted 

unsetopt BEEP # Remove annoying boop

export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=1000000000
export SAVEHIST=1000000000
export HISTTIMEFORMAT="[%F %T] "
setopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS
zmodload zsh/hist-ignore-space

autoload -U history-search-end
## Vim mode
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

autoload -Uz surround
zle -N delete-surround surround
zle -N add-surround surround
zle -N change-surround surround
bindkey -M vicmd cs change-surround
bindkey -M vicmd ds delete-surround
bindkey -M vicmd ys add-surround
bindkey -M visual S add-surround

autoload -Uz select-bracketed select-quoted
zle -N select-quoted
zle -N select-bracketed
for m in viopp visual; do
  bindkey -M $m -- '-' vi-up-line-or-history
  for c in {a,i}${(s..)^:-\'\"\`\|,./:;=+@}; do
    bindkey -M $m $c select-quoted
  done
  for c in {a,i}${(s..)^:-'()[]{}<>bB'}; do
    bindkey -M $m $c select-bracketed
  done
done

function tmux_init {
    # list all tmux sessions
    sessions=$(tmux list-sessions)
    # check if there are any sessions
    if [ -n "$sessions" ]; then
        # use awk to get the name of the first session
        session_name=$(echo "$sessions" | awk 'NR==1{print $1}')
        # initialize the first session
        tmux attach-session -t "$session_name"
    else
        # create a new session if there are no existing sessions
        tmux
    fi
}
