#!/usr/bin/env bash
zle-line-init() {
  emulate -L zsh

  [[ $CONTEXT == start ]] || return 0

  while true; do
	  zle .recursive-edit
	  local -i ret=$?
	  [[ $ret == 0 && $KEYS == $'\4' ]] || break
	  [[ -o ignore_eof ]] || exit 0
  done

  local bold=$(tput bold)
  local reset=$(tput sgr0)
  local green=$(tput setaf 2)

  local prompt_symbol=$'\u21E5'
  local saved_prompt=$PROMPT
  local saved_rprompt=$RPROMPT

  PROMPT="  $bold$green$prompt_symbol$reset "
  RPROMPT=""
  zle .reset-prompt
  PROMPT=$saved_prompt
  RPROMPT=$saved_rprompt

  if (( ret )); then
	  zle .send-break
  else
	  zle .accept-line
  fi
}

zle -N zle-line-init
