#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"
EWW="$HOME/.local/bin/eww/eww -c $HOME/.config/eww/bar"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} open \
         bar
}

## Launch or close widgets accordingly
if [[ `pgrep eww` ]]; then
	${EWW} close-all && killall eww
    run_eww
else
    run_eww
fi
